### ISSUE TITLE
Getting this  error 'Command "yarn vercel-install" exited with 126'

### ISSUE THREAD

**Issue by Sambalicious** [beeinger/vercel-private-submodule#1]
While trying to work with your workaround for private submodules on vercel. I keep getting the error. Is there anything I am doing wrong

![image](https://user-images.githubusercontent.com/52801225/154791154-0086d73d-5b68-4bce-a8f1-765f03c61233.png)

**Comment by sanathsharma** [comment]
try
```
{
    "scripts": {
        "vercel-install": "sh vercel-submodule-workaround.sh && yarn --ignore-scripts --production=false",
    }
}
```

**Comment by beeinger** [comment]
1) Have you done this first?
`chmod u+x vercel-submodule-workaround.sh`
2) I don't recommend building in the vercel-install command, this command should replace the `yarn` or `npm install` commands, not `yarn build`/`npm run build`

**Comment by Sambalicious** [comment]
> try
> 
> ```
> {
>     "scripts": {
>         "vercel-install": "sh vercel-submodule-workaround.sh && yarn --ignore-scripts --production=false",
>     }
> }
> ```

This works like a charm. Thanks
